# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_displayGrafico(object):
    def setupUi(self, displayGrafico):
        displayGrafico.setObjectName("displayGrafico")
        displayGrafico.resize(372, 360)
        displayGrafico.setMinimumSize(QtCore.QSize(372, 300))
        displayGrafico.setMaximumSize(QtCore.QSize(372, 360))
        displayGrafico.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        displayGrafico.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        displayGrafico.setWindowIcon(icon)
        displayGrafico.setLayoutDirection(QtCore.Qt.LeftToRight)
        displayGrafico.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(displayGrafico)
        self.centralwidget.setObjectName("centralwidget")
        self.addLista = QtWidgets.QPushButton(self.centralwidget)
        self.addLista.setGeometry(QtCore.QRect(250, 10, 111, 41))
        self.addLista.setObjectName("addLista")
        self.limpaLista = QtWidgets.QPushButton(self.centralwidget)
        self.limpaLista.setGeometry(QtCore.QRect(250, 60, 111, 41))
        self.limpaLista.setObjectName("limpaLista")
        self.geraGrafico = QtWidgets.QPushButton(self.centralwidget)
        self.geraGrafico.setGeometry(QtCore.QRect(10, 270, 351, 51))
        self.geraGrafico.setObjectName("geraGrafico")
        self.Normalizar = QtWidgets.QPushButton(self.centralwidget)
        self.Normalizar.setGeometry(QtCore.QRect(10, 220, 351, 41))
        self.Normalizar.setObjectName("Normalizar")
        self.recebeAcao = QtWidgets.QLineEdit(self.centralwidget)
        self.recebeAcao.setGeometry(QtCore.QRect(10, 10, 231, 41))
        self.recebeAcao.setObjectName("recebeAcao")
        self.recebeDataInicio = QtWidgets.QLineEdit(self.centralwidget)
        self.recebeDataInicio.setGeometry(QtCore.QRect(10, 120, 231, 41))
        self.recebeDataInicio.setObjectName("recebeDataInicio")
        self.displayLista = QtWidgets.QLabel(self.centralwidget)
        self.displayLista.setGeometry(QtCore.QRect(10, 60, 231, 41))
        self.displayLista.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.displayLista.setText("")
        self.displayLista.setObjectName("displayLista")
        self.addDataInicial = QtWidgets.QPushButton(self.centralwidget)
        self.addDataInicial.setGeometry(QtCore.QRect(250, 120, 111, 41))
        self.addDataInicial.setObjectName("addDataInicial")
        self.addDataFinal = QtWidgets.QPushButton(self.centralwidget)
        self.addDataFinal.setGeometry(QtCore.QRect(250, 170, 111, 41))
        self.addDataFinal.setObjectName("addDataFinal")
        self.recebeDataFinal = QtWidgets.QLineEdit(self.centralwidget)
        self.recebeDataFinal.setGeometry(QtCore.QRect(10, 170, 231, 41))
        self.recebeDataFinal.setObjectName("recebeDataFinal")
        self.grafico = QtWidgets.QFrame(self.centralwidget)
        self.grafico.setGeometry(QtCore.QRect(10, 330, 349, 18))
        self.grafico.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grafico.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grafico.setObjectName("grafico")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.grafico)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 351, 20))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        displayGrafico.setCentralWidget(self.centralwidget)

        self.retranslateUi(displayGrafico)
        QtCore.QMetaObject.connectSlotsByName(displayGrafico)

    def retranslateUi(self, displayGrafico):
        _translate = QtCore.QCoreApplication.translate
        displayGrafico.setWindowTitle(_translate("displayGrafico", "Gráficos de Ações"))
        self.addLista.setText(_translate("displayGrafico", "Adicionar ação"))
        self.limpaLista.setText(_translate("displayGrafico", "Limpar lista"))
        self.geraGrafico.setText(_translate("displayGrafico", "Gerar gráfico"))
        self.Normalizar.setText(_translate("displayGrafico", "Gerar gráfico normalizado"))
        self.recebeAcao.setPlaceholderText(_translate("displayGrafico", "Digite a ação. ex: TECN3.SA"))
        self.recebeDataInicio.setPlaceholderText(_translate("displayGrafico", "Digite a data no formato ano-mês-dia. ex: 2022-20-10"))
        self.addDataInicial.setText(_translate("displayGrafico", "Data inicial"))
        self.addDataFinal.setText(_translate("displayGrafico", "Data final"))
        self.recebeDataFinal.setPlaceholderText(_translate("displayGrafico", "Digite a data no formato ano-mês-dia. ex: 2022-20-10"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    displayGrafico = QtWidgets.QMainWindow()
    ui = Ui_displayGrafico()
    ui.setupUi(displayGrafico)
    displayGrafico.show()
    sys.exit(app.exec_())
